### ISSUE TITLE
new options page on install isn't in sync with existing Add-On Manager preferences

### ISSUE THREAD

**Issue by widox** [bookieio/bookie-firefox#10]
In the recent #8 PR, it added some duplicate code for managing preferences. One bit is that it opens this page on install & update (options.html), but it doesn't pull the existing prefs that are already saved.

It should be in sync with existing preferences so I can just hit "Save" as it opens this page everytime now.

**Comment by suryatech** [comment]
Working on it. Thanks for pointing out.

**Comment by widox** [comment]
I think it would be great to open the Add On Manager UI instead of duplicating things, which I always meant to investigate, but I'm not sure how possible that is. But keeping the data in sync between them is a good first step.

**Comment by suryatech** [comment]
During the discussions we came up with the idea of showing something very similar to the chrome extension. 

I think it is not possible to open the Add On Manager UI. I will look into it anyways.

**Comment by mitechie** [comment]
I think it might be possible to go the other way though. Can we masher or
new options page show up in the ad on manager preferences? I think right
now it uses the simple prefs but we could look at
https://developer.mozilla.org/en-US/docs/Mozilla/Preferences/Preferences_system?redirectlocale=en-US&redirectslug=Preferences/Preferences_system

**Comment by widox** [comment]
I was staying far away from XUL. :)
Also, I'm not sure how much of that you can do with a restartless SDK addon since they are steering towards the SDK instead, afaik.

**Comment by suryatech** [comment]
@widox  I was messing with component classes at first and was trying to get it to work. Then came simple prefs which literally simplified a lot things.

@mitechie Thanks for the resource. The options page isn't any different from the current preferences page. A better thing to do is open the preferences for the extension on install using BrowserOpenAddonsMgr function. I will try and get it to work properly.

**Comment by suryatech** [comment]
One major reason to use a separate options page is to show a confirmation to the user that the settings are valid. I can't think of a better way to do that. 

Your thoughts?

**Comment by widox** [comment]
Fix merged in via #11.
