### ISSUE TITLE
Specify a default `failure()` callback when making api requests

### ISSUE THREAD

**Issue by widox** [bookieio/bookie-firefox#12]
When adding a new bmark with the Browser Console open, it shows errors saying "cb.failure is not a function".

Looks like calling `failure()` is a recent addition, but not every call defines one. We ought to define a default handler so we don't throw errors willy nilly.

**Comment by suryatech** [comment]
I have always wanted to clean up the console messages. Will release a fix soon. Thanks for stressing on this @widox

**Comment by suryatech** [comment]
@widox I couldn't reproduce the errors you specified.

I have checked the console log (using make run) as well as the in-browser console for such errors and didn't find any.

**Comment by widox** [comment]
@suryatech  hmm. did you open the Tools > Web Developer > Browser Console?

here's a stacktrack it just showed me

> stack:"ApiBase/call/request<.onComplete@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/matt/.mozilla/firefox/p2z8a24g.default/extensions/jid1-zsQS9x5zIenFuw@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid1-zsqs9x5zienfuw-at-jetpack/bookie/lib/api.js:35:21
> 
> emit@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/matt/.mozilla/firefox/p2z8a24g.default/extensions/jid1-zsQS9x5zIenFuw@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:96:9
> 
> onreadystatechange@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/matt/.mozilla/firefox/p2z8a24g.default/extensions/jid1-zsQS9x5zIenFuw@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid1-zsqs9x5zienfuw-at-jetpack/bookie/lib/request.js:91:6
> "

**Comment by suryatech** [comment]
@widox The above commit should fix it. Please confirm.

**Comment by widox** [comment]
Fix merged via #16
