### ISSUE TITLE
Problem with add-on available at "https://addons.mozilla.org/en-US/firefox/addon/bookie/"

### ISSUE THREAD

**Issue by rajanwaliya** [bookieio/bookie-firefox#28]
This is just to bring into attention that the latest version available at https://addons.mozilla.org/en-US/firefox/addon/bookie/
is not working properly.
But when i tried using :
make all
cd sdk
source bin/activate
    cd ../
make run

from the clone in my system, it worked properly.
The version 0.5.0 was released on September 8, 2014 and I can see some fixes here after that.

So this is just a reminder to update the version at the mozilla site.
Thanks.

**Comment by mitechie** [comment]
I've uploaded a new 0.6 release to firefox for review. Thanks for the prod to do the release.
